Fix compile error in Jazzy
This fixes the following compile error in Jazzy (since rosbag2 release
0.26.10), which was caused by
https://github.com/ros2/rosbag2/pull/2017 and its backport to
Jazzy (https://github.com/ros2/rclcpp/pull/2902):

    src/bag2_to_image.cpp:19:10: fatal error: rosbag2_cpp/typesupport_helpers.hpp: No such file or directory
       19 | #include "rosbag2_cpp/typesupport_helpers.hpp"
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Since the same change was not backported to Humble, we need to keep
the original code to be compatible with it.

Signed-off-by: Michal Sojka <michal.sojka@cvut.cz>